matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-7.0
          packages:
            - clang-7.0
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

before_install:
    - eval "${MATRIX_EVAL}"
